package com.kalakaar.admin.danceapp;

import android.content.Context;
import android.widget.ArrayAdapter;
import android.widget.Spinner;

import java.util.ArrayList;
import java.util.List;


public class CitiesClass  {
    public static List<String> cities;
    public static void addCities(Context context, Spinner spin, final String dat){
        cities = new ArrayList<String>(){
            {
                add("City");
                if (dat.equals("Andaman & Nicobar [AN]")){
                    add("Alipur");
                    add("Arainj-Laka-Punga");
                    add("Austinabad");
                    add("Beadonabad");
                    add("Betapur");
                    add("Bindraban");
                    add("Bonington");
                    add("Brookesabad");
                    add("Calicut");
                    add("Chetamale");
                    add("Digilpur");
                    add("Dolyganj");
                    add("Geinyale");
                    add("Haddo");
                    add("Herbertabad");
                    add("Hobdaypur");
                    add("Ilichar");
                    add("Ingoie");
                    add("Karen");
                    add("Kartara");
                    add("Little Andmand");
                    add("Maimyo");
                    add("Malappuram");
                    add("Manglutan");
                    add("Manpur");
                    add("Mitha Khari");
                    add("Pahlagaon");
                    add("Palalankwe");
                    add("Phaiapong");
                    add("Port Blair");
                    add("Protheroepur");
                    add("Rangachang");
                    add("Rongat");
                    add("Sabari");
                    add("Shadipur");
                    add("Taylerabad");
                    add("Titaije");
                    add("Toibalawe");
                    add("Tusonabad");
                    add("Wimberleyganj");
                    add("Yadita");
                }else if (dat.equals("Andhra Pradesh [AP]")) {
                    add("Adilabad");
                    add("Anantapur");
                    add("Chittoor");
                    add("Kakinada");
                    add("Guntur");
                    add("Hyderabad");
                    add("Karimnagar");
                    add("Khammam");
                    add("Krishna");
                    add("Kurnool");
                    add("Mahbubnagar");
                    add("Medak");
                    add("Nalgonda");
                    add("Nizamabad");
                    add("Nellore");
                    add("Srikakulam");
                    add("Visakhapatnam");
                    add("Vizianagaram");
                    add("Warangal");
                    add("Eluru");
                    add("Kadapa");
                }else if (dat.equals("Arunachal Pradesh [AR]")){
                    add("Anjaw");
                    add("Changlang");
                    add("East Siang");
                    add("Kurung Kumey");
                    add("Lohit");
                    add("Lower Dibang Valley");
                    add("Lower Subansiri");
                    add("Papum Pare");
                    add("Tawang");
                    add("Tirap");
                    add("Dibang Valley");
                    add("Upper Siang");
                    add("Upper Subansiri");
                    add("West Kameng");
                    add("West Siang");
                }else if (dat.equals("Assam [AS]")){
                    add("Baksa");
                    add("Barpeta");
                    add("Bongaigaon");
                    add("Cachar");
                    add("Chirang");
                    add("Darrang");
                    add("Dhemaji");
                    add("Dima Hasao");
                    add("Dhubri");
                    add("Dibrugarh");
                    add("Goalpara");
                    add("Golaghat");
                    add("Hailakandi");
                    add("Jorhat");
                    add("Kamrup");
                    add("Kamrup Metropolitan");
                    add("Karbi Anglong");
                    add("Karimganj");
                    add("Kokrajhar");
                    add("Lakhimpur");
                    add("Marigaon");
                    add("Nagaon");
                    add("Nalbari");
                    add("Sibsagar");
                    add("Sonitpur");
                    add("Tinsukia");
                    add("Udalguri");
                } else if (dat.equals("Bihar [BH]")){
                    add("Araria");
                    add("Arwal");
                    add("Aurangabad");
                    add("Banka");
                    add("Begusarai");
                    add("Bhagalpur");
                    add("Bhojpur");
                    add("Buxar");
                    add("Darbhanga");
                    add("East Champaran");
                    add("Gaya");
                    add("Gopalganj");
                    add("Jamui");
                    add("Jehanabad");
                    add("Kaimur");
                    add("Katihar");
                    add("Khagaria");
                    add("Kishanganj");
                    add("Lakhisarai");
                    add("Madhepura");
                    add("Madhubani");
                    add("Munger");
                    add("Muzaffarpur");
                    add("Nalanda");
                    add("Nawada");
                    add("Patna");
                    add("Purnia");
                    add("Rohtas");
                    add("Saharsa");
                    add("Samastipur");
                    add("Saran");
                    add("Sheikhpura");
                    add("Sheohar");
                    add("Sitamarhi");
                    add("Siwan");
                    add("Supaul");
                    add("Vaishali");
                    add("West Champaran");
                } else if (dat.equals("Chandigarh [CH]")){
                    add("Chandigarh");
                    add("Mani Marja");
                } else if (dat.equals("Chhattisgarh [CG]")){
                    add("Bastar");
                    add("Bijapur");
                    add("Bilaspur");
                    add("Dantewada");
                    add("Dhamtari");
                    add("Jashpur");
                    add("Janjgir-Champa");
                    add("Korba");
                    add("Koriya");
                    add("Kanker");
                    add("Kabirdham (Kawardha)");
                    add("Mahasamund");
                    add("Narayanpur");
                    add("Raigarh");
                    add("Rajnandgaon");
                    add("Raipur");
                    add("Surguja");
                } else if (dat.equals("Dadra & Nagar Haveli [DN]")){
                    add("Amal");
                    add("Amli");
                    add("Bedpa");
                    add("Chikhli");
                    add("Dadra & Nagar Haveli");
                    add("Dahikhed");
                    add("Dolara");
                }else if (dat.equals("Daman & Diu [DD]")){
                    add("Brancavare");
                    add("Dagasi");
                    add("Daman");
                    add("Diu");
                    add("Magarvara");
                    add("Nagwa");
                    add("Pariali");
                    add("Passo Covo");
                } else if (dat.equals("Delhi [DL]")){
                    add("Central Delhi");
                    add("East Delhi");
                    add("New Delhi");
                    add("North Delhi");
                    add("North East Delhi");
                    add("North West Delhi");
                    add("South Delhi");
                    add("South West Delhi");
                    add("West Delhi");
                } else if (dat.equals("Goa [GO]")){
                    add("Canacona");
                    add("Candolim");
                    add("Chinchinim");
                    add("Cortalim");
                    add("Goa");
                    add("Jua");
                    add("Madgaon");
                    add("Mahem");
                    add("Mapuca");
                    add("Marmagao");
                    add("Panji");
                    add("Ponda");
                    add("Sanvordem");
                    add("Terekhol");
                } else if (dat.equals("Gujarat [GU]")){
                    add("Ahmedabad");
                    add("Amreli district");
                    add("Anand");
                    add("Banaskantha");
                    add("Bharuch");
                    add("Bhavnagar");
                    add("Dahod");
                    add("The Dangs");
                    add("Gandhinagar");
                    add("Jamnagar");
                    add("Junagadh");
                    add("Kutch");
                    add("Kheda");
                    add("Mehsana");
                    add("Narmada");
                    add("Navsari");
                    add("Patan");
                    add("Panchmahal");
                    add("Porbandar");
                    add("Rajkot");
                    add("Sabarkantha");
                    add("Surendranagar");
                    add("Surat");
                    add("Vyara");
                    add("Vadodara");
                    add("Valsad");
                }else if (dat.equals("Haryana [HR]")){
                    add("Ambala");
                    add("Bhiwani");
                    add("Faridabad");
                    add("Fatehabad");
                    add("Gurgaon");
                    add("Hissar");
                    add("Jhajjar");
                    add("Jind");
                    add("Kaithal");
                    add("Kurukshetra");
                    add("Mahendragarh");
                    add("Mewat");
                    add("Palwal");
                    add("Panchkula");
                    add("Panipat");
                    add("Rewari");
                    add("Rohtak");
                    add("Sirsa");
                    add("Sonipat");
                    add("Yamuna Nagar");
                }else if (dat.equals("Himachal Pradesh [HP]")){
                    add("Bilaspur");
                    add("Chamba");
                    add("Hamirpur");
                    add("Kangra");
                    add("Kinnaur");
                    add("Kullu");
                    add("Lahaul and Spiti");
                    add("Mandi");
                    add("Shimla");
                    add("Sirmaur");
                    add("Solan");
                    add("Una");
                } else if (dat.equals("Jammu & Kashmir [JK]")){
                    add("Anantnag");
                    add("Badgam");
                    add("Bandipora");
                    add("Baramulla");
                    add("Doda");
                    add("Ganderbal");
                    add("Jammu");
                    add("Kargil");
                    add("Kathua");
                    add("Kishtwar");
                    add("Kupwara");
                    add("Kulgam");
                    add("Leh");
                    add("Poonch");
                    add("Pulwama");
                    add("Rajauri");
                    add("Ramban");
                    add("Reasi");
                    add("Samba");
                    add("Shopian");
                    add("Srinagar");
                    add("Udhampur");
                }else if (dat.equals("Jharkhand [JH]")){
                    add("Bokaro");
                    add("Chatra");
                    add("Deoghar");
                    add("Dhanbad");
                    add("Dumka");
                    add("East Singhbhum");
                    add("Garhwa");
                    add("Giridih");
                    add("Godda");
                    add("Gumla");
                    add("Hazaribag");
                    add("Jamtara");
                    add("Khunti");
                    add("Koderma");
                    add("Latehar");
                    add("Lohardaga");
                    add("Pakur");
                    add("Palamu");
                    add("Ramgarh");
                    add("Ranchi");
                    add("Sahibganj");
                    add("Seraikela Kharsawan");
                    add("Simdega");
                    add("West Singhbhum");
                } else if (dat.equals("Karnataka [KR]")){
                    add("Bagalkot");
                    add("Bangalore Rural");
                    add("Bangalore Urban");
                    add("Belgaum");
                    add("Bellary");
                    add("Bidar");
                    add("Bijapur");
                    add("Chamarajnagar");
                    add("Chikkamagaluru");
                    add("Chikkaballapur");
                    add("Chitradurga");
                    add("Davanagere");
                    add("Dharwad");
                    add("Dakshina Kannada");
                    add("Gadag");
                    add("Gulbarga");
                    add("Hassan");
                    add("Haveri district");
                    add("Kodagu");
                    add("Kolar");
                    add("Koppal");
                    add("Mandya");
                    add("Mysore");
                    add("Raichur");
                    add("Shimoga");
                    add("Tumkur");
                    add("Udupi");
                    add("Uttara Kannada");
                    add("Ramanagara");
                    add("Yadgir");
                } else if (dat.equals("Kerala [KL]")){
                    add("Alappuzha");
                    add("Ernakulam");
                    add("Idukki");
                    add("Kannur");
                    add("Kasaragod");
                    add("Kollam");
                    add("Kottayam");
                    add("Kozhikode");
                    add("Malappuram");
                    add("Palakkad");
                    add("Pathanamthitta");
                    add("Thrissur");
                    add("Thiruvananthapuram");
                    add("Wayanad");
                } else if (dat.equals("Lakshadweep [LD]")){
                    add("Agatti Island");
                    add("Bingaram Island");
                    add("Bitra Island");
                    add("Chetlat Island");
                    add("Kadmat Island");
                    add("Kalpeni Island");
                    add("Kavaratti Island");
                    add("Kiltan Island");
                    add("Lakshadweep Sea");
                    add("Minicoy Island");
                    add("North Island");
                    add("South Island");
                } else if (dat.equals("Madhya Pradesh [MP]")){
                    add("Alirajpur");
                    add("Anuppur");
                    add("Ashok Nagar");
                    add("Balaghat");
                    add("Barwani");
                    add("Betul");
                    add("Bhind");
                    add("Bhopal");
                    add("Burhanpur");
                    add("Chhatarpur");
                    add("Chhindwara");
                    add("Damoh");
                    add("Datia");
                    add("Dewas");
                    add("Dhar");
                    add("Dindori");
                    add("Guna");
                    add("Gwalior");
                    add("Harda");
                    add("Hoshangabad");
                    add("Indore");
                    add("Jabalpur");
                    add("Jhabua");
                    add("Katni");
                    add("Khandwa (East Nimar)");
                    add("Khargone (West Nimar)");
                    add("Mandla");
                    add("Mandsaur");
                    add("Morena");
                    add("Narsinghpur");
                    add("Neemuch");
                    add("Panna");
                    add("Rewa");
                    add("Rajgarh");
                    add("Ratlam");
                    add("Raisen");
                    add("Sagar");
                    add("Satna");
                    add("Sehore");
                    add("Seoni");
                    add("Shahdol");
                    add("Shajapur");
                    add("Sheopur");
                    add("Shivpuri");
                    add("Sidhi");
                    add("Singrauli");
                    add("Tikamgarh");
                    add("Ujjain");
                    add("Umaria");
                    add("Vidisha");
                } else if (dat.equals("Maharashtra [MH]")){
                    add("Ahmednagar");
                    add("Akola");
                    add("Amravati");
                    add("Aurangabad");
                    add("Bhandara");
                    add("Beed");
                    add("Buldhana");
                    add("Chandrapur");
                    add("Dhule");
                    add("Gadchiroli");
                    add("Gondia");
                    add("Hingoli");
                    add("Jalgaon");
                    add("Jalna");
                    add("Kolhapur");
                    add("Latur");
                    add("Mumbai City");
                    add("Mumbai suburban");
                    add("Nandurbar");
                    add("Nanded");
                    add("Nagpur");
                    add("Nashik");
                    add("Osmanabad");
                    add("Parbhani");
                    add("Pune");
                    add("Raigad");
                    add("Ratnagiri");
                    add("Sindhudurg");
                    add("Sangli");
                    add("Solapur");
                    add("Satara");
                    add("Thane");
                    add("Wardha");
                    add("Washim");
                    add("Yavatmal");
                } else if (dat.equals("Manipur [MN]")){
                    add("Bishnupur");
                    add("Churachandpur");
                    add("Chandel");
                    add("Imphal East");
                    add("Senapati");
                    add("Tamenglong");
                    add("Thoubal");
                    add("Ukhrul");
                    add("Imphal West");
                } else if (dat.equals("Meghalaya [ML]")){
                    add("East Garo Hills");
                    add("East Khasi Hills");
                    add("Jaintia Hills");
                    add("Ri Bhoi");
                    add("South Garo Hills");
                    add("West Garo Hills");
                    add("West Khasi Hills");
                } else if (dat.equals("Mizoram [MM]")){
                    add("Aizawl");
                    add("Champhai");
                    add("Kolasib");
                    add("Lawngtlai");
                    add("Lunglei");
                    add("Mamit");
                    add("Saiha");
                    add("Serchhip");
                } else if (dat.equals("Nagaland [NL]")){
                    add("Dimapur");
                    add("Kohima");
                    add("Mokokchung");
                    add("Mon");
                    add("Phek");
                    add("Tuensang");
                    add("Wokha");
                    add("Zunheboto");
                } else if (dat.equals("Orissa [OR]")){
                    add("Angul");
                    add("Boudh (Bauda)");
                    add("Bhadrak");
                    add("Balangir");
                    add("Bargarh (Baragarh)");
                    add("Balasore");
                    add("Cuttack");
                    add("Debagarh (Deogarh)");
                    add("Dhenkanal");
                    add("Ganjam");
                    add("Gajapati");
                    add("Jharsuguda");
                    add("Jajpur");
                    add("Jagatsinghpur");
                    add("Khordha");
                    add("Kendujhar (Keonjhar)");
                    add("Kalahandi");
                    add("Kandhamal");
                    add("Koraput");
                    add("Kendrapara");
                    add("Malkangiri");
                    add("Mayurbhanj");
                    add("Nabarangpur");
                    add("Nuapada");
                    add("Nayagarh");
                    add("Puri");
                    add("Rayagada");
                    add("Sambalpur");
                    add("Subarnapur (Sonepur)");
                    add("Sundergarh");
                } else if (dat.equals("Pondicherry [PC]")){
                    add("Karaikal");
                    add("Mahe");
                    add("Pondicherry");
                    add("Yanam");
                } else if (dat.equals("Punjab [PJ]")){
                    add("Amritsar");
                    add("Barnala");
                    add("Bathinda");
                    add("Firozpur");
                    add("Faridkot");
                    add("Fatehgarh Sahib");
                    add("Fazilka");
                    add("Gurdaspur");
                    add("Hoshiarpur");
                    add("Jalandhar");
                    add("Kapurthala");
                    add("Ludhiana");
                    add("Mansa");
                    add("Moga");
                    add("Sri Muktsar Sahib");
                    add("Pathankot");
                    add("Patiala");
                    add("Rupnagar");
                    add("Ajitgarh (Mohali)");
                    add("Sangrur");
                    add("Nawanshahr");
                    add("Tarn Taran");
                } else if (dat.equals("Rajasthan [RJ]")){
                    add("Ajmer");
                    add("Alwar");
                    add("Bikaner");
                    add("Barmer");
                    add("Banswara");
                    add("Bharatpur");
                    add("Baran");
                    add("Bundi");
                    add("Bhilwara");
                    add("Churu");
                    add("Chittorgarh");
                    add("Dausa");
                    add("Dholpur");
                    add("Dungapur");
                    add("Ganganagar");
                    add("Hanumangarh");
                    add("Jhunjhunu");
                    add("Jalore");
                    add("Jodhpur");
                    add("Jaipur");
                    add("Jaisalmer");
                    add("Jhalawar");
                    add("Karauli");
                    add("Kota");
                    add("Nagaur");
                    add("Pali");
                    add("Pratapgarh");
                    add("Rajsamand");
                    add("Sikar");
                    add("Sawai Madhopur");
                    add("Sirohi");
                    add("Tonk");
                    add("Udaipur");
                } else if (dat.equals("Sikkim [SK]")){
                    add("East Sikkim");
                    add("North Sikkim");
                    add("South Sikkim");
                    add("West Sikkim");
                } else if (dat.equals("Tamil Nadu [TN]")){
                    add("Ariyalur");
                    add("Chennai");
                    add("Coimbatore");
                    add("Cuddalore");
                    add("Dharmapuri");
                    add("Dindigul");
                    add("Erode");
                    add("Kanchipuram");
                    add("Kanyakumari");
                    add("Karur");
                    add("Madurai");
                    add("Nagapattinam");
                    add("Nilgiris");
                    add("Namakkal");
                    add("Perambalur");
                    add("Pudukkottai");
                    add("Ramanathapuram");
                    add("Salem");
                    add("Sivaganga");
                    add("Tirupur");
                    add("Tiruchirappalli");
                    add("Theni");
                    add("Tirunelveli");
                    add("Thanjavur");
                    add("Thoothukudi");
                    add("Tiruvallur");
                    add("Tiruvarur");
                    add("Tiruvannamalai");
                    add("Vellore");
                    add("Viluppuram");
                    add("Virudhunagar");
                } else if (dat.equals("Tripura [TR]")){
                    add("Agartala");
                    add("Ambasa");
                    add("Bampurbari");
                    add("Belonia");
                    add("Dhalai");
                    add("Dharam Nagar");
                    add("Kailashahar");
                    add("Kamal Krishnabari");
                    add("Khopaiyapara");
                    add("Khowai");
                    add("Phuldungsei");
                    add("Radha Kishore Pur");
                    add("Tripura");
                } else if (dat.equals("Uttar Pradesh [UP]")){
                    add("Agra");
                    add("Allahabad");
                    add("Aligarh");
                    add("Ambedkar Nagar");
                    add("Auraiya");
                    add("Azamgarh");
                    add("Barabanki");
                    add("Budaun");
                    add("Bagpat");
                    add("Bahraich");
                    add("Bijnor");
                    add("Ballia");
                    add("Banda");
                    add("Balrampur");
                    add("Bareilly");
                    add("Basti");
                    add("Bulandshahr");
                    add("Chandauli");
                    add("Chhatrapati Shahuji Maharaj Nagar");
                    add("Chitrakoot");
                    add("Deoria");
                    add("Etah");
                    add("Kanshi Ram Nagar");
                    add("Etawah");
                    add("Firozabad");
                    add("Farrukhabad");
                    add("Fatehpur");
                    add("Faizabad");
                    add("Gautam Buddh Nagar");
                    add("Gonda");
                    add("Ghazipur");
                    add("Gorakhpur");
                    add("Ghaziabad");
                    add("Hamirpur");
                    add("Hardoi");
                    add("Mahamaya Nagar");
                    add("Jhansi");
                    add("Jalaun");
                    add("Jyotiba Phule Nagar");
                    add("Jaunpur district");
                    add("Ramabai Nagar (Kanpur Dehat)");
                    add("Kannauj");
                    add("Kanpur");
                    add("Kaushambi");
                    add("Kushinagar");
                    add("Lalitpur");
                    add("Lakhimpur Kheri");
                    add("Lucknow");
                    add("Mau");
                    add("Meerut");
                    add("Maharajganj");
                    add("Mahoba");
                    add("Mirzapur");
                    add("Moradabad");
                    add("Mainpuri");
                    add("Mathura");
                    add("Muzaffarnagar");
                    add("Panchsheel Nagar district (Hapur)");
                    add("Pilibhit");
                    add("Shamli");
                    add("Pratapgarh");
                    add("Rampur");
                    add("Raebareli");
                    add("Saharanpur");
                    add("Sitapur");
                    add("Shahjahanpur");
                    add("Sant Kabir Nagar");
                    add("Siddharthnagar");
                    add("Sonbhadra");
                    add("Sant Ravidas Nagar");
                    add("Sultanpur");
                    add("Shravasti");
                    add("Unnao");
                    add("Varanasi");
                } else if (dat.equals("Uttaranchal [UT]")){
                    add("Almora");
                    add("Bageshwar");
                    add("Chamoli");
                    add("Champawat");
                    add("Dehradun");
                    add("Haridwar");
                    add("Nainital");
                    add("Pauri Garhwal");
                    add("Pithoragarh");
                    add("Rudraprayag");
                    add("Tehri Garhwal");
                    add("Udham Singh Nagar");
                    add("Uttarkashi");
                } else if (dat.equals("West Bengal [WB]")){
                    add("Birbhum");
                    add("Bankura");
                    add("Bardhaman");
                    add("Darjeeling");
                    add("Dakshin Dinajpur");
                    add("Hooghly");
                    add("Howrah");
                    add("Jalpaiguri");
                    add("Cooch Behar");
                    add("Kolkata");
                    add("Maldah");
                    add("Paschim Medinipur");
                    add("Purba Medinipur");
                    add("Murshidabad");
                    add("Nadia");
                    add("North 24 Parganas");
                    add("South 24 Parganas");
                    add("Purulia");
                    add("Uttar Dinajpur");
                }else {

                }
            }};
        ArrayAdapter<String> adp4 = new ArrayAdapter<String>(context, R.layout.spinner_item, cities);
        spin.setAdapter(adp4);
    }

}
