package com.kalakaar.admin.danceapp;

import android.content.Context;
import android.widget.ArrayAdapter;
import android.widget.Spinner;

import java.util.ArrayList;
import java.util.List;

public class StateNames {
    public static List<String> state;
    public static void addStates(Context context, Spinner spin, final String dat) {
        state = new ArrayList<String>() {
            {
                add("State");
                if (dat.equals("Australia")) {
                    add("New South Wales");
                    add("Queensland");
                    add("South Australia");
                    add("Tasmania");
                    add("Victoria");
                    add("Western Australia");
                } else if (dat.equals("USA")) {
                    add("Alaska");
                    add("Arizona");
                    add("Arkansas");
                    add("California");
                    add("Colorado");
                    add("Connecticut");
                    add("Delaware");
                    add("Florida");
                    add("Georgia");
                    add("Georgia");
                    add("Idaho");
                    add("Illinois");
                    add("Indiana");
                    add("Iowa");
                    add("Kansas");
                    add("Kentucky");
                    add("Louisiana");
                    add("Maine");
                    add("Maryland");
                    add("Massachusetts");
                    add("Michigan");
                    add("Minnesota");
                    add("Mississippi");
                    add("Missouri");
                    add("Montana");
                    add("Nebraska");
                    add("Nevada");
                    add("New Hampshire");
                    add("New Jersey");
                    add("New Mexico");
                    add("New York");
                    add("North Carolina");
                    add("North Dakota");
                    add("Ohio");
                    add("Oklahoma");
                    add("Oregon");
                    add("Pennsylvania");
                    add("Rhode Island");
                    add("South Carolina");
                    add("South Dakota");
                    add("Tennessee");
                    add("Texas");
                    add("Utah");
                    add("Vermont");
                    add("Virginia");
                    add("Washington");
                    add("West Virginia");
                    add("Wisconsin");
                    add("Wyoming");
                } else if (dat.equals("United Kingdom")) {
                    add("Aberdeen");
                    add("Bath And North East Somerset");
                    add("Belfast ");
                    add("Bournemouth");
                    add("Brighton And Hove");
                    add("Bristol");
                    add("Cambridgeshire");
                    add("Cardiff");
                    add("Cheshire");
                    add("Cornwall");
                    add("Cumbria");
                    add("Londonderry");
                    add("Devon");
                    add("Dumfries And Galloway");
                    add("Dundee");
                    add("Dungannon");
                    add("Edinburgh");
                    add("Glasgow");
                    add("Highland");
                    add("Inverclyde");
                    add("Kent");
                    add("Kingston Upon Hull");
                    add("Blackpool");
                    add("Leicester");
                    add("Luton");
                    add("Manchester");
                    add("Merseyside");
                    add("Moray");
                    add("Norfolk");
                    add("North Yorkshire");
                    add("Nottingham");
                    add("Omagh");
                    add("Oxfordshire");
                    add("Perthshire And Kinross");
                    add("Peterborough");
                    add("Plymouth");
                    add("Portsmouth");
                    add("South Ayrshire");
                    add("South Yorkshire");
                    add("Southampton");
                    add("Southend On Sea");
                    add("Stockton On Tees");
                    add("Stoke On Trent");
                    add("Suffolk");
                    add("Swansea");
                    add("Tyne And Wear");
                    add("West Midlands");
                    add("West Yorkshire");
                    add("Westminster");
                    add("York");
                } else if (dat.equals("Austria")) {
                    add("Vienna (Wien)");
                    add("Lower Austria");
                    add("Upper Austria");
                    add("Styria (Steiermark)");
                    add("Tyrol (Tirol)");
                    add("Carinthia (Kärnten)");
                    add("Salzburg");
                    add("Vorarlberg");
                    add("Burgen");
                } else if (dat.equals("Argentina")) {
                    add("Catamarca");
                    add("Chaco");
                    add("Chubut");
                    add("Ciudad De Buenos Aires");
                    add("Cordoba");
                    add("Corrientes ");
                    add("Entre Rios");
                    add("Formosa ");
                    add("Jujuy ");
                    add("La Pampa");
                    add("La Rioja");
                    add("Mendoza ");
                    add("Misiones ");
                    add("Neuquen ");
                    add("Rio Negro");
                    add("Salta ");
                    add("San Juan");
                    add("San Luis");
                    add("Santa Cruz");
                    add("Santa Fe");
                    add("Santiago Del Estero");
                    add("Tierra Del Fuego");
                    add("Tucuman");
                } else if (dat.equals("Bangladesh")) {
                    add("Barisal");
                    add("Chittagong");
                    add("Dhaka");
                    add("Khulna");
                    add("Rajshahi");
                    add("Sylhet");
                } else if (dat.equals("Belgium")) {
                    add("Antwerp");
                    add("Arlon");
                    add("Brugge");
                    add("Brussels");
                    add("Charleroi");
                    add("East Flanders");
                    add("Hainaut");
                    add("Liege");
                    add("Limburg");
                    add("Namur");
                } else if (dat.equals("Bhutan")) {
                    add("Punakha");
                    add("Thimphu");
                    add("Wangdi Phodrang");
                } else if (dat.equals("Brazil")) {
                    add("Acre ");
                    add("Alagoas ");
                    add("Amapa ");
                    add("Amazonas ");
                    add("Bahia ");
                    add("Ceara ");
                    add("Distrito Federal");
                    add("Espirito Santo");
                    add("Goias ");
                    add("Maranhao ");
                    add("Mato Grosso");
                    add("Mato Grosso Do Sul");
                    add("Minas Gerais");
                    add("Para");
                    add("Paraiba");
                    add("Parana");
                    add("Pernambuco");
                    add("Piaui");
                    add("Rio De Janeiro");
                    add("Rio Grande Do Norte");
                    add("Rio Grande Do Sul");
                    add("Rondonia ");
                    add("Roraima ");
                    add("Santa Catarina");
                    add("Sao Paulo");
                    add("Sergipe ");
                    add("Tocantins ");
                } else if (dat.equals("Canada")) {
                    add("Alberta ");
                    add("British Columbia");
                    add("Manitoba ");
                    add("New Brunswick");
                    add("Newfoundland And Labrador");
                    add("Northwest Territories");
                    add("Nova Scotia");
                    add("Nunavut ");
                    add("Ontario ");
                    add("Prince Edward Island");
                    add("Quebec ");
                    add("Saskatchewan ");
                    add("Yukon ");
                } else if (dat.equals("Chile")) {
                    add("Aisen Del");
                    add("Antofagasta ");
                    add("Arica Y Parinacota");
                    add("Atacama ");
                    add("Bio Bio");
                    add("Coquimbo ");
                    add("La Araucania");
                    add("Libertador General");
                    add("Los Lagos");
                    add("Los Rios");
                    add("Magallanes Y Antartica");
                    add("Maule ");
                    add("Region Metropolitana");
                    add("Santa Cruz");
                    add("Tarapaca ");
                    add("Valparaiso ");
                } else if (dat.equals("China")) {
                    add("Anhui ");
                    add("Beijing ");
                    add("Chongqing ");
                    add("Fujian ");
                    add("Gansu ");
                    add("Guangdong ");
                    add("Guangxi ");
                    add("Guizhou ");
                    add("Hainan ");
                    add("Hebei ");
                    add("Heilongjiang ");
                    add("Henan ");
                    add("Hubei ");
                    add("Hunan ");
                    add("Jiangsu ");
                    add("Jiangxi ");
                    add("Jilin ");
                    add("Liaoning");
                    add("Nei Mongol");
                    add("Ningxia Hui");
                    add("Shaanxi ");
                    add("Shandong ");
                    add("Shanghai ");
                    add("Shanxi ");
                    add("Sichuan ");
                    add("Tianjin ");
                    add("Xinjiang Uygur");
                    add("Xizang");
                    add("Yunnan ");
                    add("Zhejiang");
                } else if (dat.equals("Germany")) {
                    add("Baden-Württemberg");
                    add(" Bavaria");
                    add(" Berlin");
                    add(" Brandenburg");
                    add(" Bremen");
                    add(" Hamburg");
                    add(" Hesse");
                    add("Lower Saxony");
                    add("Mecklenburg-Western");
                    add("North Rhine-Westphalia");
                    add("Rhineland-Palatinate");
                    add(" Saarland");
                    add(" Saxony");
                    add("Saxony-Anhalt");
                    add("Schleswig-Holstein");
                    add(" Thuringia");
                } else if (dat.equals("India")) {
                    add("Andaman & Nicobar [AN]");
                    add("Andhra Pradesh [AP]");
                    add("Arunachal Pradesh [AR]");
                    add("Assam [AS]");
                    add("Bihar [BH]");
                    add("Chandigarh [CH]");
                    add("Chhattisgarh [CG]");
                    add("Dadra & Nagar Haveli [DN]");
                    add("Daman & Diu [DD]");
                    add("Delhi [DL]");
                    add("Goa [GO]");
                    add("Gujarat [GU]");
                    add("Haryana [HR]");
                    add("Himachal Pradesh [HP]");
                    add("Jammu & Kashmir [JK]");
                    add("Jharkhand [JH]");
                    add("Karnataka [KR]");
                    add("Kerala [KL]");
                    add("Lakshadweep [LD]");
                    add("Madhya Pradesh [MP]");
                    add("Maharashtra [MH]");
                    add("Manipur [MN]");
                    add("Meghalaya [ML]");
                    add("Mizoram [MM]");
                    add("Nagaland [NL]");
                    add("Orissa [OR]");
                    add("Pondicherry [PC]");
                    add("Punjab [PJ]");
                    add("Rajasthan [RJ]");
                    add("Sikkim [SK]");
                    add("Tamil Nadu [TN]");
                    add("Tripura [TR]");
                    add("Uttar Pradesh [UP]");
                    add("Uttaranchal [UT]");
                    add("West Bengal [WB]");
                } else if (dat.equals("Indonesia")) {
                    add("Aceh ");
                    add("Bali ");
                    add("Bangka Belitung");
                    add("Banten ");
                    add("Bengkulu");
                    add("Gorontalo");
                    add("Irian Jaya Barat");
                    add("Jakarta Raya");
                    add("Jambi");
                    add("Jawa Barat");
                    add("Jawa Tengah");
                    add("Jawa Timur");
                    add("Kalimantan Barat");
                    add("Kalimantan Selatan");
                    add("Kalimantan Tengah");
                    add("Kalimantan Timur");
                    add("Kepulauan Riau");
                    add("Lampung ");
                    add("Maluku");
                    add("Maluku Utara");
                    add("Nusa Tenggara Barat");
                    add("Nusa Tenggara Timur");
                    add("Papua ");
                    add("Riau ");
                    add("Sulawesi Barat");
                    add("Sulawesi Selatan");
                    add("Sulawesi Tengah");
                    add("Sulawesi Tenggara");
                    add("Sulawesi Utara");
                    add("Sumatera Barat");
                    add("Sumatera Selatan");
                    add("Sumatera Utara");
                    add("Yogyakarta");
                } else if (dat.equals("Italy")) {
                    add("Abruzzo");
                    add("Apulia");
                    add("Basilicata ");
                    add("Calabria");
                    add("Campania ");
                    add("Emilia Romagna");
                    add("Friuli Venezia Giulia");
                    add("Lazio");
                    add("Liguria");
                    add("Lombardia");
                    add("Marche ");
                    add("Molise");
                    add("Piemonte");
                    add("Sardegna ");
                    add("Sicily ");
                    add("Toscana ");
                    add("Trentino Alto Adige");
                    add("Umbria ");
                    add("Valle D'aosta");
                    add("Veneto");
                } else if (dat.equals("Georgia")) {
                    add("Abkhazia ");
                    add("Ajaria ");
                    add("Imereti ");
                    add("Kvemo Kartli");
                    add("Samegrelo Zemo Svaneti");
                    add("Shida Kartli");
                    add("Tbilisi");
                } else if (dat.equals("Hungery")) {
                    add("Bacs Kiskun");
                    add("Barany");
                    add("Bekes ");
                    add("Borsod Abauj Zemplen");
                    add("Budapest ");
                    add("Csongrad ");
                    add("Fejer ");
                    add("Gyor Moson Sopron");
                    add("Hajdu Bihar");
                    add("Heves ");
                    add("Jasz Nagykun Szolnok");
                    add("Komarom Esztergom");
                    add("Nograd ");
                    add("Pest ");
                    add("Somogy ");
                    add("Szabolcs Szatmar Bereg");
                    add("Tolna ");
                    add("Vas ");
                    add("Veszprem ");
                    add("Zala  ");
                } else if (dat.equals("Malaysia")) {
                    add("Johor ");
                    add("Kedah ");
                    add("Kelantan ");
                    add("Melaka ");
                    add("Negeri Sembilan");
                    add("Pahang ");
                    add("Perak ");
                    add("Perlis ");
                    add("Pulau Pinang");
                    add("Sabah ");
                    add("Sarawak ");
                    add("Selangor ");
                    add("Trengganu");
                } else if (dat.equals("Mexico")) {
                    add("Aguascalientes  ");
                    add("Baja California");
                    add("Baja California Sur");
                    add("Campeche");
                    add("Chiapas");
                    add("Chihuahua");
                    add("Coahuila ");
                    add("Colima ");
                    add("Distrito Federa");
                    add("Durango");
                    add("Guanajuato  ");
                    add("Guerrero");
                    add("Hidalgo ");
                    add("Jalisco ");
                    add("Mexico ");
                    add("Michoacan");
                    add("Morelos");
                    add("Nayarit ");
                    add("Nuevo Leon");
                    add("Oaxaca ");
                    add("Puebla");
                    add("Queretaro");
                    add("Jhabua");
                    add("Quintana Roo");
                    add("San Luis Potosi");
                    add("Sinaloa");
                    add("Sonora");
                    add("Tabasco ");
                    add("Tamaulipas");
                    add("Tlaxcala");
                    add("Veracruz");
                    add("Yucatan");
                    add("Zacatecas ");
                } else {

                }
            }
        };
        ArrayAdapter<String> adp4 = new ArrayAdapter<String>(context, R.layout.spinner_item, state);
        spin.setAdapter(adp4);
    }
}
